---
# Kueue's own view of the fleet, scraped into Managed Prometheus: what each
# ClusterQueue holds against its quota, how long a workload waited before it was
# admitted, and whether it was admitted at all or evicted. Buildkite can say a
# step took three hours; only this can say how much of that was queueing and how
# many chips sat idle while it queued.
#
# On every cluster, not just the manager. The manager admits against fleet quota
# and the worker admits again against its own, so a workload that is pending is
# pending on one of them, and which one is the whole question.
#
# Managed Prometheus is the only monitoring stack these clusters run - GKE
# installs its CRDs and collectors, and the Prometheus Operator is not present,
# so ServiceMonitor is not a thing that exists here.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${SCRAPER_NAME}
  namespace: ${SCRAPER_NAMESPACE}
---
# Kueue serves metrics over TLS behind controller-runtime's authn/authz filter,
# so a scrape is a request the API server has to authenticate and Kueue has to
# authorize. kueue-metrics-reader is upstream's role for exactly this and grants
# nothing but GET on the /metrics URL; binding is all that is left to do.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ${SCRAPER_NAME}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kueue-metrics-reader
subjects:
- kind: ServiceAccount
  name: ${SCRAPER_NAME}
  namespace: ${SCRAPER_NAMESPACE}
---
# A token the collector can send. It has to be this rather than a projected
# volume because the collector reads its credential from a Secret and nothing
# else, and it has to be a Secret the token controller fills rather than one we
# write, so no credential for this cluster exists outside it.
apiVersion: v1
kind: Secret
metadata:
  name: ${SCRAPER_NAME}-token
  namespace: ${SCRAPER_NAMESPACE}
  annotations:
    kubernetes.io/service-account.name: ${SCRAPER_NAME}
type: kubernetes.io/service-account-token
---
# The collector fetches the token itself - it is the process that makes the
# scrape - and GKE ships it with no access to ${SCRAPER_NAMESPACE} at all, so
# without this it logs "secret watcher failed to start" and the target stays
# down. Named to this one Secret, so anything else put in the namespace later is
# not included by having been put there.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ${SCRAPER_NAME}-token-reader
  namespace: ${SCRAPER_NAMESPACE}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["${SCRAPER_NAME}-token"]
  verbs: ["get", "list", "watch"]
---
# The subject is GKE's collector, whose name and namespace are managed
# collection's rather than ours; it is the DaemonSet that does every scrape on
# this cluster, including the two here.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ${SCRAPER_NAME}-token-reader
  namespace: ${SCRAPER_NAMESPACE}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ${SCRAPER_NAME}-token-reader
subjects:
- kind: ServiceAccount
  name: collector
  namespace: gmp-system
---
# Cluster-scoped rather than a PodMonitoring in kueue-system, because of where
# the Secret above has to live. The operator's only grant to read Secrets is a
# Role in ${SCRAPER_NAMESPACE}; a namespaced PodMonitoring resolves a credential
# against its own namespace, which the operator cannot read. Scoping is not lost
# by this - the selector matches the controller pod and nothing else runs with
# those labels.
apiVersion: monitoring.googleapis.com/v1
kind: ClusterPodMonitoring
metadata:
  name: kueue
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kueue
      control-plane: controller-manager
  endpoints:
  - port: metrics
    scheme: https
    # The serving certificate is generated by the controller at startup for its
    # own pod IP and signed by nobody, so there is no CA to pin it to. The hop
    # is pod-to-pod inside the cluster and the token is what proves the scrape
    # is allowed; verifying the certificate would only be verifying it against
    # itself.
    tls:
      insecureSkipVerify: true
    authorization:
      type: Bearer
      credentials:
        secret:
          namespace: ${SCRAPER_NAMESPACE}
          name: ${SCRAPER_NAME}-token
          key: token
    # A workload is admitted, runs for an hour and finishes; the quota gauges
    # move at the speed of admissions, not of scrapes. 30s is fine for that and
    # keeps the sample count - every controller-runtime and Go runtime series
    # comes along with the kueue_ ones - down.
    interval: 30s
