#!/bin/bash
set -euo pipefail
if [ "${1:-}" = get ]; then
  export _BK_TEMP_GITHUB_APP_PEM
  _BK_TEMP_GITHUB_APP_PEM="$(buildkite-agent secret get GITHUB_CI_BOT_PEM)"
  /opt/tpu-ci/venv/bin/python /etc/buildkite-agent/get-github-token.py
  unset _BK_TEMP_GITHUB_APP_PEM
fi
