# Temporary test pipeline - tests the launch template update step
# Delete after testing

env:
  SSM_PARAM_US_EAST_1: "/buildkite/cpu-build-ami/us-east-1"

steps:
  - label: ":rocket: Test Update Launch Templates"
    command:
      - |
        set -euo pipefail

        echo "--- :aws: Updating Launch Templates with new AMI"

        # Get the new AMI ID from SSM
        NEW_AMI=$$(aws ssm get-parameter \
          --name "$${SSM_PARAM_US_EAST_1}" \
          --query 'Parameter.Value' \
          --output text \
          --region us-east-1)

        echo "New AMI ID: $$NEW_AMI"

        # ASG names follow the pattern: <stack-name>-AgentAutoScaleGroup-<random>
        # We need to find them dynamically
        for STACK_PREFIX in bk-cpu-queue-premerge-us-east-1 bk-cpu-queue-postmerge-us-east-1; do
          echo "--- Processing $$STACK_PREFIX"

          # Find the ASG for this stack
          ASG_NAME=$$(aws autoscaling describe-auto-scaling-groups \
            --query "AutoScalingGroups[?starts_with(AutoScalingGroupName, '$$STACK_PREFIX')].AutoScalingGroupName" \
            --output text \
            --region us-east-1)

          if [[ -z "$$ASG_NAME" ]]; then
            echo "Warning: No ASG found for $$STACK_PREFIX"
            continue
          fi

          echo "Found ASG: $$ASG_NAME"

          # Get the launch template ID from the ASG
          # Check both direct LaunchTemplate and MixedInstancesPolicy.LaunchTemplate
          LT_ID=$$(aws autoscaling describe-auto-scaling-groups \
            --auto-scaling-group-names "$$ASG_NAME" \
            --query 'AutoScalingGroups[0].MixedInstancesPolicy.LaunchTemplate.LaunchTemplateSpecification.LaunchTemplateId || AutoScalingGroups[0].LaunchTemplate.LaunchTemplateId' \
            --output text \
            --region us-east-1)

          if [[ -z "$$LT_ID" || "$$LT_ID" == "None" || "$$LT_ID" == "null" ]]; then
            echo "Warning: No launch template found for ASG $$ASG_NAME"
            continue
          fi

          echo "Found Launch Template: $$LT_ID"

          # Create a new launch template version with the new AMI
          NEW_VERSION=$$(aws ec2 create-launch-template-version \
            --launch-template-id "$$LT_ID" \
            --source-version '$$Latest' \
            --launch-template-data "{\"ImageId\": \"$$NEW_AMI\"}" \
            --query 'LaunchTemplateVersion.VersionNumber' \
            --output text \
            --region us-east-1)

          echo "Created new launch template version: $$NEW_VERSION"

          # Update the ASG to use the new launch template version
          # Use mixed-instances-policy since that's how the ASG is configured
          aws autoscaling update-auto-scaling-group \
            --auto-scaling-group-name "$$ASG_NAME" \
            --mixed-instances-policy "LaunchTemplate={LaunchTemplateSpecification={LaunchTemplateId=$$LT_ID,Version=$$NEW_VERSION}}" \
            --region us-east-1

          echo "Updated ASG $$ASG_NAME to use launch template version $$NEW_VERSION"
        done

        echo ""
        echo "Launch templates updated. New instances will use AMI: $$NEW_AMI"
        echo "Existing instances will continue running until they complete their jobs."
    agents:
      queue: packer_build_queue
    timeout_in_minutes: 10
